global using CheatForm.Settings.Base;
global using CheatL4D2.Graphics;
global using CheatL4D2.Settings;
global using CheatL4D2.Settings.Enums;
global using Hack;
global using Hack.Models;
global using Overlay;
global using System;
global using System.Diagnostics;
global using System.Drawing;
global using System.Windows.Forms;
global using SystemGraphics = System.Drawing.Graphics;